Test against the current hhvm version
equip/assist pull request #24
Opened 2016-11-29 19:01 UTC by photodude

You are currently testing on an old EOL version of HHVM 3.6.6 (a limitation of precise on Travis)

This PR provides the current HHVM version (3.15.3 as of this PR) and will track with each release (i.e. will be 3.16 when 3.16 is released).

If testing against HHVM LST versions is desired follow this guide. https://docs.travis-ci.com/user/languages/php#HHVM-versions

Should be able to change to container based Trusty after Q1-17 https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/

Additionally adds php 7.1 and switches most tests to the faster Travis-CI Container Infrastructure

2016-11-29 19:18 UTC, shadowhand requested changes

2016-11-29 19:18 UTC, shadowhand commented on .travis.yml
> +sudo: false
Travis already defaults to `sudo: false`.

2016-11-29 19:19 UTC, shadowhand approved these changes

2016-11-29 19:19 UTC, shadowhand commented
:+1:

2016-11-29 19:21 UTC, photodude commented on .travis.yml
> +sudo: false
Yes, but you can run into issues with mixed `sudo: true` and the default `sudo: false`. Small line addition to ensure less testing issues.

2016-11-29 19:25 UTC, merged

2016-11-29 19:25 UTC, shadowhand commented
Thanks!

2016-11-30 02:45 UTC, photodude commented
You are welcome @shadowhand